# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Microsoft Azure Sponsorship - XDRA(12daf2f0-3f23-4963-9fc4-31f48e9d0af3)'
    subscriptionId: '12daf2f0-3f23-4963-9fc4-31f48e9d0af3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOPsVMTest'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
